replicaCount: 2

image:
  repository: fastapi-tasks
  tag: "1.4"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: NodePort
  port: 8000
  nodePort: 30008

env:
  FAIL_HEALTH: "false"

config:
  APP_NAME: "FastAPI Tasks"
  ENVIRONMENT: "dev"

 # commenting for testing 
